name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - feature/*

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install pnpm using version from packageManager in package.json
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      # Setup .npmrc file to publish to GitHub Packages
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

      - name: Lint
        run: pnpm run lint

      - name: Spelling
        run: pnpm run check:spelling

      # - name: Test
      #   run: pnpm run test

      - name: Build
        run: pnpm run build

      - name: Publish npm package
        if: success() && github.ref == 'refs/heads/main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm publish --provenance --access public

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
